spring:
  application:
    name: my-favorite-items
  servlet:
    multipart:
      enabled: true
      location: /tmp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_favorite_items?useServerPrepStmts=false&rewriteBatchedStatements=true&characterEncoding=utf8&characterSetResults=utf8&connectTimeout=600000&socketTimeout=600000&zeroDateTimeBehavior=convertToNull&useSSL=false&requireSSL=false&jdbcCompliantTruncation=false&logger=com.mysql.jdbc.log.Slf4JLogger&profileSQL=true
    username: root

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
  servlet:
    mapping: /graphql
    enabled: true
    cors-enabled: true
    cors:
      allowed-methods: GET, HEAD, POST
    exception-handlers-enabled: true
